language: java

matrix:
  include:
  - os: linux
    jdk: oraclejdk8
  - os: linux
    jdk: oraclejdk9
  - os: linux
    dist: xenial
    jdk: openjdk10
  - os: linux
    dist: xenial
    jdk: openjdk11
  - os: osx
    osx_image: xcode9.3 # JDK 8
  - os: osx
    osx_image: xcode10.1 # JDK 11
